export const videosList = [
    {
        "category": "Introduction",
        "browseable": true,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-001-welcome.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-001-welcome-to-skincoach-v9-1537879927395/es-001-welcome-to-skincoach-v9-master-playlist.m3u8",
        "description": "Welcome to Skincoach from Dra Pilar García-Muret.",
        "title": "Welcome to Skincoach",
        "baseTags": [
            "introduction",
            "intro",
            "pilar",
            "dra",
            "garcia",
            "muret",
            "welcome",
            "skincoach",
            "getting started",
            "start",
            "help"
        ],
        "baseTitle": "Welcome to Skincoach",
        "tags": [
            "introduction",
            "intro",
            "pilar",
            "dra",
            "garcia",
            "muret",
            "welcome",
            "skincoach",
            "getting started",
            "start",
            "help"
        ],
        "slug": "welcome-to-skincoach",
        "runningTime": 86,
        "baseCategory": "Introduction",
        "active": true,
        "baseDescription": "Welcome to Skincoach from Dra Pilar García-Muret.",
        "id": 1,
        "url": "https://video.skincoachapp.com/v1/_debug/welcome-to-skincoach.json"
    },
    {
        "category": "Introduction",
        "browseable": true,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-003-how-does-my-treatment-work.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-003-how-does-my-treatment-work-v9-1537879952427/es-003-how-does-my-treatment-work-v9-master-playlist.m3u8",
        "description": "What is an EGFR inhibitor & why do skin reactions occur.",
        "title": "How does my treatment work?",
        "baseTags": [
            "EGFR",
            "inhibitor",
            "skin reaction",
            "treatment",
            "cancer cell",
            "follicle",
            "why",
            "how",
            "what"
        ],
        "baseTitle": "How does my treatment work?",
        "tags": [
            "EGFR",
            "inhibitor",
            "skin reaction",
            "treatment",
            "cancer cell",
            "follicle",
            "why",
            "how",
            "what"
        ],
        "slug": "how-does-my-treatment-work",
        "runningTime": 125,
        "baseCategory": "Introduction",
        "active": true,
        "baseDescription": "What is an EGFR inhibitor & why do skin reactions occur.",
        "id": 3,
        "url": "https://video.skincoachapp.com/v1/_debug/how-does-my-treatment-work.json"
    },
    {
        "category": "Tips",
        "browseable": true,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-004-avoid-the-sun.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-004-avoid-the-sun-v9-1537879926928/es-004-avoid-the-sun-v9-master-playlist.m3u8",
        "description": "Simple advice for reducing your exposure to the sun.",
        "title": "Avoid the sun",
        "baseTags": [
            "sun",
            "sunlight",
            "tips",
            "advice",
            "sunscreen",
            "sunblock",
            "suncream",
            "UV",
            "sun burn",
            "SPF",
            "swimming",
            "clothing",
            ""
        ],
        "baseTitle": "Avoid the sun",
        "tags": [
            "sun",
            "sunlight",
            "tips",
            "advice",
            "sunscreen",
            "sunblock",
            "suncream",
            "UV",
            "sun burn",
            "SPF",
            "swimming",
            "clothing",
            ""
        ],
        "slug": "avoid-the-sun",
        "runningTime": 78,
        "baseCategory": "Tips",
        "active": true,
        "baseDescription": "Simple advice for reducing your exposure to the sun.",
        "id": 4,
        "url": "https://video.skincoachapp.com/v1/_debug/avoid-the-sun.json"
    },
    {
        "category": "Tips",
        "browseable": true,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-005-simple-prevention-tips.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-005-simple-prevention-tips-v9-1537879954142/es-005-simple-prevention-tips-v9-master-playlist.m3u8",
        "description": "Simple recommendations that may help your treatment.",
        "title": "Simple prevention tips",
        "baseTags": [
            "antiseptic soap",
            "daily routine",
            "skincare routine",
            "wash",
            "bath",
            "shower",
            "sauna",
            "swimming",
            "chlolrine",
            "water",
            "moisturise",
            "bacteria",
            "infection",
            "skin",
            "itch",
            "perfume",
            "fragrance",
            "toothpaste",
            "laundry",
            "detergent",
            "clothes",
            "clothing",
            "gloves",
            "shoes",
            "make-up",
            "cosmetics",
            "finger",
            "toe",
            "nails",
            "pedicure",
            "manicure",
            "nail polish",
            "shaving",
            "razor",
            "beard"
        ],
        "baseTitle": "Simple prevention tips",
        "tags": [
            "antiseptic soap",
            "daily routine",
            "skincare routine",
            "wash",
            "bath",
            "shower",
            "sauna",
            "swimming",
            "chlolrine",
            "water",
            "moisturise",
            "bacteria",
            "infection",
            "skin",
            "itch",
            "perfume",
            "fragrance",
            "toothpaste",
            "laundry",
            "detergent",
            "clothes",
            "clothing",
            "gloves",
            "shoes",
            "make-up",
            "cosmetics",
            "finger",
            "toe",
            "nails",
            "pedicure",
            "manicure",
            "nail polish",
            "shaving",
            "razor",
            "beard"
        ],
        "slug": "simple-prevention-tips",
        "runningTime": 413,
        "baseCategory": "Tips",
        "active": true,
        "baseDescription": "Simple recommendations that may help your treatment.",
        "id": 5,
        "url": "https://video.skincoachapp.com/v1/_debug/simple-prevention-tips.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": true,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-006-common-side-effects.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-006-common-side-effects-and-symptoms-v9-1537879974674/es-006-common-side-effects-and-symptoms-v9-master-playlist.m3u8",
        "description": "The different types of common skin reactions and their symptoms.",
        "title": "Common skin reactions",
        "baseTags": [
            "common",
            "frequent",
            "skin",
            "condition",
            "symptoms",
            "rash",
            "pimple",
            "folicular",
            "redness",
            "ithcy",
            "acneiform",
            "dry skin",
            "xerosis",
            "fissures",
            "crack",
            "nail",
            "eyelash",
            "trichomegaly",
            "hyperpigmentation",
            "paronychia",
            "time",
            "frequency",
            "stages",
            "day",
            "week",
            "month",
            "face",
            "neck",
            "chest",
            "scalp",
            "fingers",
            "toes",
            "heels",
            "feet",
            "foot",
            "hand",
            "inflammation",
            "treatment"
        ],
        "baseTitle": "Common skin reactions",
        "tags": [
            "common",
            "frequent",
            "skin",
            "condition",
            "symptoms",
            "rash",
            "pimple",
            "folicular",
            "redness",
            "ithcy",
            "acneiform",
            "dry skin",
            "xerosis",
            "fissures",
            "crack",
            "nail",
            "eyelash",
            "trichomegaly",
            "hyperpigmentation",
            "paronychia",
            "time",
            "frequency",
            "stages",
            "day",
            "week",
            "month",
            "face",
            "neck",
            "chest",
            "scalp",
            "fingers",
            "toes",
            "heels",
            "feet",
            "foot",
            "hand",
            "inflammation",
            "treatment"
        ],
        "slug": "common-skin-reactions",
        "runningTime": 153,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "The different types of common skin reactions and their symptoms.",
        "id": 6,
        "url": "https://video.skincoachapp.com/v1/_debug/common-skin-reactions.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-007-skin-rash-1.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-007-skin-rash-1-v9-1537879946715/es-007-skin-rash-1-v9-master-playlist.m3u8",
        "description": "Mild redness, flushing and pimples on the face, scalp or torso.",
        "title": "Mild folicular rash",
        "baseTags": [
            "mild",
            "rash",
            "follicular",
            "aceniform",
            "redness",
            "flushing",
            "pimple",
            "spot",
            "face",
            "chin",
            "scalp",
            "neck",
            "torso",
            "chest"
        ],
        "baseTitle": "Mild folicular rash",
        "tags": [
            "mild",
            "rash",
            "follicular",
            "aceniform",
            "redness",
            "flushing",
            "pimple",
            "spot",
            "face",
            "chin",
            "scalp",
            "neck",
            "torso",
            "chest"
        ],
        "slug": "mild-folicular-rash",
        "runningTime": 139,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Mild redness, flushing and pimples on the face, scalp or torso.",
        "id": 7,
        "url": "https://video.skincoachapp.com/v1/_debug/mild-folicular-rash.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-008-skin-rash-2.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-008-skin-rash-2-v9-1537879967765/es-008-skin-rash-2-v9-master-playlist.m3u8",
        "description": "Redness, flushing, pimples and pustules on the face, scalp, neck, chest or back.",
        "title": "Moderate folicular rash",
        "baseTags": [
            "moderate",
            "rash",
            "follicular",
            "redness",
            "flushing",
            "pimples",
            "pustules",
            "zits",
            "spots",
            "face",
            "scalp",
            "chest",
            "back",
            "neck",
            "torso",
            "chin"
        ],
        "baseTitle": "Moderate folicular rash",
        "tags": [
            "moderate",
            "rash",
            "follicular",
            "redness",
            "flushing",
            "pimples",
            "pustules",
            "zits",
            "spots",
            "face",
            "scalp",
            "chest",
            "back",
            "neck",
            "torso",
            "chin"
        ],
        "slug": "moderate-folicular-rash",
        "runningTime": 133,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Redness, flushing, pimples and pustules on the face, scalp, neck, chest or back.",
        "id": 8,
        "url": "https://video.skincoachapp.com/v1/_debug/moderate-folicular-rash.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-009-skin-rash-3.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-009-skin-rash-3-v9-1537879960932/es-009-skin-rash-3-v9-master-playlist.m3u8",
        "description": "A high density of itchy and inflamed pimples and pustules. This may be a sign of infection.",
        "title": "Severe folicular rash",
        "baseTags": [
            "severe",
            "rash",
            "follicular",
            "acneiform",
            "itch",
            "inflamed",
            "pimple",
            "pustule",
            "rash",
            "redness",
            "spot",
            "zit",
            "infection",
            "face",
            "chin",
            "scalp",
            "chest",
            "back",
            "neck",
            "torso"
        ],
        "baseTitle": "Severe folicular rash",
        "tags": [
            "severe",
            "rash",
            "follicular",
            "acneiform",
            "itch",
            "inflamed",
            "pimple",
            "pustule",
            "rash",
            "redness",
            "spot",
            "zit",
            "infection",
            "face",
            "chin",
            "scalp",
            "chest",
            "back",
            "neck",
            "torso"
        ],
        "slug": "severe-folicular-rash",
        "runningTime": 31,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "A high density of itchy and inflamed pimples and pustules. This may be a sign of infection.",
        "id": 9,
        "url": "https://video.skincoachapp.com/v1/_debug/severe-folicular-rash.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-010-nail-changes-1.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-010-nail-changes-1-v9-1537879959847/es-010-nail-changes-1-v9-master-playlist.m3u8",
        "description": "Swelling and redness around the finger or toenails.",
        "title": "Mild paronychia",
        "baseTags": [
            "mild",
            "nail",
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "inflammation",
            "paronychia",
            "swelling",
            "redness",
            "shoes",
            "pain",
            "brittle"
        ],
        "baseTitle": "Mild paronychia",
        "tags": [
            "mild",
            "nail",
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "inflammation",
            "paronychia",
            "swelling",
            "redness",
            "shoes",
            "pain",
            "brittle"
        ],
        "slug": "mild-paronychia",
        "runningTime": 95,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Swelling and redness around the finger or toenails.",
        "id": 10,
        "url": "https://video.skincoachapp.com/v1/_debug/mild-paronychia.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-011-nail-changes-2.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-011-nail-changes-2-v9-1537879952047/es-011-nail-changes-2-v9-master-playlist.m3u8",
        "description": "Painful swelling & redness around the finger or toenails.",
        "title": "Moderate paronychia",
        "baseTags": [
            "moderate",
            "nail",
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "inflammation",
            "paronychia",
            "swelling",
            "redness",
            "shoes",
            "pain",
            "brittle",
            "fluid",
            "discharge"
        ],
        "baseTitle": "Moderate paronychia",
        "tags": [
            "moderate",
            "nail",
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "inflammation",
            "paronychia",
            "swelling",
            "redness",
            "shoes",
            "pain",
            "brittle",
            "fluid",
            "discharge"
        ],
        "slug": "moderate-paronychia",
        "runningTime": 128,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Painful swelling & redness around the finger or toenails.",
        "id": 11,
        "url": "https://video.skincoachapp.com/v1/_debug/moderate-paronychia.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-012-nail-changes-3.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-012-nail-changes-3-v9-1537879966011/es-012-nail-changes-3-v9-master-playlist.m3u8",
        "description": "Painful swelling & redness around the finger or toenails with discharge or nailplate separation.",
        "title": "Severe paronychia",
        "baseTags": [
            "swelling",
            "nail",
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "inflammation",
            "paronychia",
            "swelling",
            "redness",
            "shoes",
            "pain",
            "brittle",
            "fluid",
            "discharge",
            "very",
            "nailplate",
            "separation"
        ],
        "baseTitle": "Severe paronychia",
        "tags": [
            "swelling",
            "nail",
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "inflammation",
            "paronychia",
            "swelling",
            "redness",
            "shoes",
            "pain",
            "brittle",
            "fluid",
            "discharge",
            "very",
            "nailplate",
            "separation"
        ],
        "slug": "severe-paronychia",
        "runningTime": 40,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Painful swelling & redness around the finger or toenails with discharge or nailplate separation.",
        "id": 12,
        "url": "https://video.skincoachapp.com/v1/_debug/severe-paronychia.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-013-dry-skin.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-013-xerosis-dry-skin-v9-1537879979366/es-013-xerosis-dry-skin-v9-master-playlist.m3u8",
        "description": "Rough, dry and flaky skin, it may have some discomfort and itching.",
        "title": "Dry or scaly skin",
        "baseTags": [
            "xerosis",
            "dry",
            "rough",
            "flake",
            "flaking",
            "itch",
            "scales",
            "scaling",
            "scratch",
            "irritate"
        ],
        "baseTitle": "Dry or scaly skin",
        "tags": [
            "xerosis",
            "dry",
            "rough",
            "flake",
            "flaking",
            "itch",
            "scales",
            "scaling",
            "scratch",
            "irritate"
        ],
        "slug": "dry-or-scaly-skin",
        "runningTime": 201,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Rough, dry and flaky skin, it may have some discomfort and itching.",
        "id": 13,
        "url": "https://video.skincoachapp.com/v1/_debug/dry-or-scaly-skin.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-014-fissures-mild-and-moderate.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-014-mild-to-moderate-fissures-v9-1537880026000/es-014-mild-to-moderate-fissures-v9-master-playlist.m3u8",
        "description": "Cracks in the skin on the fingers, and heels.",
        "title": "Mild to moderate fissures",
        "baseTags": [
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "heel",
            "dry",
            "crack",
            "fissure",
            "thin",
            "finger pads",
            ""
        ],
        "baseTitle": "Mild to moderate fissures",
        "tags": [
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "heel",
            "dry",
            "crack",
            "fissure",
            "thin",
            "finger pads",
            ""
        ],
        "slug": "mild-to-moderate-fissures",
        "runningTime": 99,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Cracks in the skin on the fingers, and heels.",
        "id": 14,
        "url": "https://video.skincoachapp.com/v1/_debug/mild-to-moderate-fissures.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-015-fissures-severe.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-015-severe-fissures-v9-1537879984707/es-015-severe-fissures-v9-master-playlist.m3u8",
        "description": "Painful cracks or fissures on the fingertips, toes and heels.",
        "title": "Severe fissures",
        "baseTags": [
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "heel",
            "dry",
            "crack",
            "fissure",
            "thin",
            "finger pads",
            "severe",
            "pain"
        ],
        "baseTitle": "Severe fissures",
        "tags": [
            "finger",
            "toe",
            "hand",
            "foot",
            "feet",
            "heel",
            "dry",
            "crack",
            "fissure",
            "thin",
            "finger pads",
            "severe",
            "pain"
        ],
        "slug": "severe-fissures",
        "runningTime": 33,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Painful cracks or fissures on the fingertips, toes and heels.",
        "id": 15,
        "url": "https://video.skincoachapp.com/v1/_debug/severe-fissures.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-018-eczema.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-018-eczema-v9-1537879961174/es-018-eczema-v9-master-playlist.m3u8",
        "description": "Patches of skin become inflamed, itchy, red, cracked and rough.",
        "title": "Eczema",
        "baseTags": [
            "eczema",
            "itch",
            "inflamed",
            "scale",
            "scaling",
            "cracked",
            "patchy",
            "red"
        ],
        "baseTitle": "Eczema",
        "tags": [
            "eczema",
            "itch",
            "inflamed",
            "scale",
            "scaling",
            "cracked",
            "patchy",
            "red"
        ],
        "slug": "eczema",
        "runningTime": 78,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Patches of skin become inflamed, itchy, red, cracked and rough.",
        "id": 18,
        "url": "https://video.skincoachapp.com/v1/_debug/eczema.json"
    },
    {
        "category": "Common skin reactions",
        "browseable": false,
        "thumbUrl": "https://video.skincoachapp.com/content/thumbs/es-019-eyelash-changes.jpg",
        "videoUrl": "https://video.skincoachapp.com/content/hls/es-019-trichomegaly-v9-1537880010867/es-019-trichomegaly-v9-master-playlist.m3u8",
        "description": "Long, curly, rigid eyelashes.",
        "title": "Eyelash changes",
        "baseTags": [
            "eyelash",
            "hair",
            "follicle",
            "trichomegally",
            "curly",
            "long",
            "rigid",
            "eye",
            "follicle"
        ],
        "baseTitle": "Eyelash changes",
        "tags": [
            "eyelash",
            "hair",
            "follicle",
            "trichomegally",
            "curly",
            "long",
            "rigid",
            "eye",
            "follicle"
        ],
        "slug": "eyelash-changes",
        "runningTime": 42,
        "baseCategory": "Common skin reactions",
        "active": true,
        "baseDescription": "Long, curly, rigid eyelashes.",
        "id": 19,
        "url": "https://video.skincoachapp.com/v1/_debug/eyelash-changes.json"
    }
  ];